services:
  mysql:
    image: "mysql:latest"
    environment:
      - "MYSQL_DATABASE=telecom"
      - "MYSQL_PASSWORD=angel1052"
      - "MYSQL_ROOT_PASSWORD=angel1052"
      - "MYSQL_USER=angel"
    ports:
      - "3307:3306"
